{{- if and .Values.repos .Values.repos.gitlab }}
{{- $gitlab := .Values.gitlab -}}
{{- $globals := .Values.globals -}}
{{- $name := .Values.name -}}
{{- $refresh := include "chart.refresh" . -}}
{{- $retryBackoffDuration := include "chart.retryBackoffDuration" . -}}
{{- $namespace := include "chart.namespace" . -}}
{{- $dqf := "{{" -}}
{{- $dqb := "}}" -}}
{{- $branch := "{{branch}}" | squote -}}
{{- $branchSlug := "{{branch_slug}}" | squote -}}
{{- $headShortSha := "{{head_short_sha}}" | squote -}}
{{- $server := include "chart.server" . -}}
{{- $notificationChannel := include "chart.notificationChannel" . -}}

{{- range $key, $repo := .Values.repos.gitlab }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ required "A valid repo name is required" $repo.name | trunc 40 | trimSuffix "-" }}-gitlab-{{ $name }}'
  namespace: {{ required "A valid namespace is required" $namespace | replace "." "-" }}
  labels:
    app.kubernetes.io/name: {{ $repo.name }}
    app.kubernetes.io/platform: 'gitlab'
  annotations:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  {{- if eq $server "all" }}
  - clusters: {}
  {{- end }}
  - pullRequest:
      gitlab:
        api: {{ $gitlab.api }}
        project: {{ coalesce $repo.project $gitlab.group |  required "A valid repo project / group ID is required" | squote}}
        pullRequestState: 'opened'
        labels:
        - {{ required "A valid label(s) for PRs is required" (coalesce $gitlab.label $globals.label) }}
        {{- if and ($gitlab.secretName) ($gitlab.secretKey) }}
        tokenRef:
          secretName: {{ $gitlab.secretName }}
          key: {{ $gitlab.secretKey }}
        {{- end }}
      requeueAfterSeconds: {{ $refresh | default 500 }}
  template:
    metadata:
      name: {{ printf "%s-%sbranch_slug%s-%snumber%s-%s" $repo.name $dqf $dqb $dqf $dqb $name}}
      labels:
        app.kubernetes.io/name: {{ $repo.name }}
        app.kubernetes.io/branch: {{ trunc 63 $branchSlug | trimSuffix "-" }}
        app.kubernetes.io/created-by: 'applicationset'
      annotations:
        argocd.argoproj.io/head: {{ $headShortSha }}
        link.argocd.argoproj.io/external-link: '{{ $gitlab.api }}/{{ $gitlab.group }}/{{or $repo.name $repo.path}}/-/merge_requests/{{ $dqf }}number{{ $dqb }}'
        {{- with $globals.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      revisionHistoryLimit: {{ $globals.revisionHistoryLimit }}
      source:
        {{- $localRepoUrl := printf "%s/%s/%s.git" $gitlab.api $gitlab.group $repo.name }}
        repoURL: {{ coalesce $repo.repoUrl $localRepoUrl }}
        {{- if and $repo $repo.parameters }}
        helm:
          parameters:
            {{ toJson $repo.parameters | indent 0 }}
        chart: {{ or $repo.chart $repo.name }}
        targetRevision: {{ or $repo.targetRevision ">= 0" | quote }}
        {{- else if and $repo $repo.values }}
        helm:
          values: |
            {{ toJson $repo.values | indent 0 }}
        {{- if and $repo $repo.chart }}
        chart: {{ or $repo.chart $repo.name }}
        {{- else if and $repo $repo.path }}
        path: {{ $repo.path }}
        {{- end }}
        targetRevision: {{ or $repo.targetRevision $branch $headShortSha "HEAD" }}
        {{- else }}
        targetRevision: {{ or $repo.targetRevision $branch $headShortSha "HEAD" }}
        kustomize:
          commonAnnotations:
            app.kubernetes.io/instance: '{{ $repo.name }}'
            app.kubernetes.io/part-of: {{ coalesce $gitlab.label $globals.label }}
            argocd.argoproj.io/head_short_sha: '{{ $dqf }}head_short_sha{{ $dqb }}'
          {{- range $i, $r := $repo.images }}
          {{- if eq $i 0 }}
          images:
          {{- end }}
          - {{ $r | indent 0 | squote }}
          {{- end }}
        path: {{ coalesce $repo.path $gitlab.path }}
        {{- end }}
      project: {{ and $.Values.project $.Values.project.enabled | ternary $name "default" }}
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        {{- range $s := $globals.syncOptions }}
          - {{ $s }}
        {{- end }}
        retry:
          backoff:
            duration: {{ $retryBackoffDuration }}
      destination:
        {{- if eq $server "all" }}
        server: '{{ $dqf }}server{{ $dqb }}'
        {{- else }}
        server: {{ $server }}
        {{- end }}
        namespace: {{ coalesce $repo.namespace $.Values.globals.deployToNamespace (printf "mr-%sbranch_slug%s-%snumber%s" $dqf $dqb $dqf $dqb) }}
      info:
        - name: author
          value: '{{ $dqf }}author{{ $dqb }}'
        - name: branch
          value: '{{ $dqf }}branch{{ $dqb }}'
        - name: target_branch
          value: '{{ $dqf }}target_branch_slug{{ $dqb }}'
        - name: branch_slug
          value: '{{ $dqf }}branch_slug{{ $dqb }}'
        - name: merge_request
          value: '{{ $dqf }}number{{ $dqb }}'
{{- end }}
{{- end }}
